<?php
namespace My\NamespaceName;
class Classy extends \Chiara\PodioApplicationStructure
{
    protected $APPID = "2345";
    protected $APPNAME = "Application";
    protected $structure = array (
      'title' => 
      array (
        'type' => 'text',
        'name' => 'title',
        'id' => 51928207,
        'config' => NULL,
      ),
      51928207 => 
      array (
        'type' => 'text',
        'name' => 'title',
        'id' => 51928207,
        'config' => NULL,
      ),
      'contact' => 
      array (
        'type' => 'contact',
        'name' => 'contact',
        'id' => 51928208,
        'config' => 'space_users',
      ),
      51928208 => 
      array (
        'type' => 'contact',
        'name' => 'contact',
        'id' => 51928208,
        'config' => 'space_users',
      ),
      'contact-2' => 
      array (
        'type' => 'contact',
        'name' => 'contact-2',
        'id' => 51928209,
        'config' => 'space_contacts',
      ),
      51928209 => 
      array (
        'type' => 'contact',
        'name' => 'contact-2',
        'id' => 51928209,
        'config' => 'space_contacts',
      ),
      'category' => 
      array (
        'type' => 'category',
        'name' => 'category',
        'id' => 51928210,
        'config' => 
        array (
          'options' => 
          array (
            0 => 
            array (
              'status' => 'active',
              'text' => '1',
              'id' => 1,
              'color' => 'DCEBD8',
            ),
            1 => 
            array (
              'status' => 'active',
              'text' => '2',
              'id' => 2,
              'color' => 'DCEBD8',
            ),
          ),
          'multiple' => false,
        ),
      ),
      51928210 => 
      array (
        'type' => 'category',
        'name' => 'category',
        'id' => 51928210,
        'config' => 
        array (
          'options' => 
          array (
            0 => 
            array (
              'status' => 'active',
              'text' => '1',
              'id' => 1,
              'color' => 'DCEBD8',
            ),
            1 => 
            array (
              'status' => 'active',
              'text' => '2',
              'id' => 2,
              'color' => 'DCEBD8',
            ),
          ),
          'multiple' => false,
        ),
      ),
      'date' => 
      array (
        'type' => 'date',
        'name' => 'date',
        'id' => 51928211,
        'config' => NULL,
      ),
      51928211 => 
      array (
        'type' => 'date',
        'name' => 'date',
        'id' => 51928211,
        'config' => NULL,
      ),
      'link' => 
      array (
        'type' => 'embed',
        'name' => 'link',
        'id' => 51928212,
        'config' => NULL,
      ),
      51928212 => 
      array (
        'type' => 'embed',
        'name' => 'link',
        'id' => 51928212,
        'config' => NULL,
      ),
      'image' => 
      array (
        'type' => 'image',
        'name' => 'image',
        'id' => 51928213,
        'config' => NULL,
      ),
      51928213 => 
      array (
        'type' => 'image',
        'name' => 'image',
        'id' => 51928213,
        'config' => NULL,
      ),
      'google-maps' => 
      array (
        'type' => 'location',
        'name' => 'google-maps',
        'id' => 51928214,
        'config' => NULL,
      ),
      51928214 => 
      array (
        'type' => 'location',
        'name' => 'google-maps',
        'id' => 51928214,
        'config' => NULL,
      ),
      'question' => 
      array (
        'type' => 'question',
        'name' => 'question',
        'id' => 51928215,
        'config' => 
        array (
          'options' => 
          array (
            0 => 
            array (
              'status' => 'active',
              'text' => '3',
              'id' => 1,
              'color' => 'DCEBD8',
            ),
            1 => 
            array (
              'status' => 'active',
              'text' => '4',
              'id' => 2,
              'color' => 'DCEBD8',
            ),
          ),
          'multiple' => false,
        ),
      ),
      51928215 => 
      array (
        'type' => 'question',
        'name' => 'question',
        'id' => 51928215,
        'config' => 
        array (
          'options' => 
          array (
            0 => 
            array (
              'status' => 'active',
              'text' => '3',
              'id' => 1,
              'color' => 'DCEBD8',
            ),
            1 => 
            array (
              'status' => 'active',
              'text' => '4',
              'id' => 2,
              'color' => 'DCEBD8',
            ),
          ),
          'multiple' => false,
        ),
      ),
      'number' => 
      array (
        'type' => 'number',
        'name' => 'number',
        'id' => 51928216,
        'config' => NULL,
      ),
      51928216 => 
      array (
        'type' => 'number',
        'name' => 'number',
        'id' => 51928216,
        'config' => NULL,
      ),
      'money' => 
      array (
        'type' => 'money',
        'name' => 'money',
        'id' => 51928217,
        'config' => 
        array (
          0 => 'EUR',
          1 => 'DKK',
          2 => 'USD',
        ),
      ),
      51928217 => 
      array (
        'type' => 'money',
        'name' => 'money',
        'id' => 51928217,
        'config' => 
        array (
          0 => 'EUR',
          1 => 'DKK',
          2 => 'USD',
        ),
      ),
      'duration' => 
      array (
        'type' => 'duration',
        'name' => 'duration',
        'id' => 51928218,
        'config' => NULL,
      ),
      51928218 => 
      array (
        'type' => 'duration',
        'name' => 'duration',
        'id' => 51928218,
        'config' => NULL,
      ),
      'progress-slider' => 
      array (
        'type' => 'progress',
        'name' => 'progress-slider',
        'id' => 51928219,
        'config' => NULL,
      ),
      51928219 => 
      array (
        'type' => 'progress',
        'name' => 'progress-slider',
        'id' => 51928219,
        'config' => NULL,
      ),
      'calculation' => 
      array (
        'type' => 'calculation',
        'name' => 'calculation',
        'id' => 51928244,
        'config' => NULL,
      ),
      51928244 => 
      array (
        'type' => 'calculation',
        'name' => 'calculation',
        'id' => 51928244,
        'config' => NULL,
      ),
      'app-reference' => 
      array (
        'type' => 'app',
        'name' => 'app-reference',
        'id' => 51928220,
        'config' => 
        array (
          0 => 6686618,
        ),
      ),
      51928220 => 
      array (
        'type' => 'app',
        'name' => 'app-reference',
        'id' => 51928220,
        'config' => 
        array (
          0 => 6686618,
        ),
      ),
    );
}
